#!/bin/bash
#
#  Copyright (c) 2020, The OpenThread Authors.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#

set -exo pipefail

OT_CMAKE_NINJA_TARGET=${OT_CMAKE_NINJA_TARGET:-}

readonly OT_SRCDIR="$(pwd)"
readonly OT_OPTIONS_TRANSCEIVER_K32W0_UART_FLOW_CONTROL=(
    "-DBUILD_TESTING=OFF"
    "-DCMAKE_TOOLCHAIN_FILE=cmake/toolchain/arm-none-eabi.cmake"
    "-DCMAKE_BUILD_TYPE=Debug"
    "-DOT_NXP_EXPORT_TO_BIN=ON"
    "-DOT_PLATFORM=external"
    "-DOT_SLAAC=ON"
    "-DOT_SERVICE=ON"
    "-DOT_PING_SENDER=ON"
    "-DOT_EXTERNAL_HEAP=ON"
    "-DOT_EXTERNAL_MBEDTLS=nxp-rt1170-mbedtls"
    "-DOT_STACK_ENABLE_LOG=OFF"
    "-DOT_APP_NCP=OFF"
    "-DOT_APP_RCP=OFF"
    "-DOT_RCP=OFF"
    # Default OT app cli is disabled, instead a freeRTOS version of the CLI is built
    "-DOT_APP_CLI=OFF"
    "-DOT_APP_CLI_FREERTOS=ON"
    "-DOT_NXP_PLATFORM_FAMILY=imx_rt"
    "-DOT_NXP_PLATFORM=rt1170"
    "-DOT_NXP_BOARD=rt1170"
    "-DSPINEL_INTERFACE_TYPE=UART"
    "-DOT_NXP_TRANSCEIVER=k32w0"
    "-DOT_NXP_TRANSCEIVER_BIN_PATH=build_k32w061/rcp_only_uart_flow_control/bin/ot-rcp.elf.bin.h"
    "-DMULTICORE_LOGGING=OFF"
    "-DOT_COMPILE_WARNING_AS_ERROR=ON"
)
readonly OT_OPTIONS_TRANSCEIVER_K32W0_SPI=(
    "-DBUILD_TESTING=OFF"
    "-DCMAKE_TOOLCHAIN_FILE=cmake/toolchain/arm-none-eabi.cmake"
    "-DCMAKE_BUILD_TYPE=Debug"
    "-DOT_NXP_EXPORT_TO_BIN=ON"
    "-DOT_PLATFORM=external"
    "-DOT_SLAAC=ON"
    "-DOT_SERVICE=ON"
    "-DOT_PING_SENDER=ON"
    "-DOT_EXTERNAL_HEAP=ON"
    "-DOT_EXTERNAL_MBEDTLS=nxp-rt1170-mbedtls"
    "-DOT_STACK_ENABLE_LOG=OFF"
    "-DOT_APP_NCP=OFF"
    "-DOT_APP_RCP=OFF"
    "-DOT_RCP=OFF"
    # Default OT app cli is disabled, instead a freeRTOS version of the CLI is built
    "-DOT_APP_CLI=OFF"
    "-DOT_APP_CLI_FREERTOS=ON"
    "-DOT_NXP_PLATFORM_FAMILY=imx_rt"
    "-DOT_NXP_PLATFORM=rt1170"
    "-DOT_NXP_BOARD=rt1170"
    "-DSPINEL_INTERFACE_TYPE=SPI"
    "-DOT_NXP_TRANSCEIVER=k32w0"
    "-DOT_NXP_TRANSCEIVER_BIN_PATH=build_k32w061/rcp_only_spi/bin/ot-rcp.elf.bin.h"
    "-DMULTICORE_LOGGING=OFF"
    "-DOT_COMPILE_WARNING_AS_ERROR=ON"
)

readonly OT_OPTIONS_TRANSCEIVER_IWX12_SPI=(
    "-DBUILD_TESTING=OFF"
    "-DCMAKE_TOOLCHAIN_FILE=cmake/toolchain/arm-none-eabi.cmake"
    "-DCMAKE_BUILD_TYPE=Debug"
    "-DOT_NXP_EXPORT_TO_BIN=ON"
    "-DOT_PLATFORM=external"
    "-DOT_SLAAC=ON"
    "-DOT_SERVICE=ON"
    "-DOT_PING_SENDER=ON"
    "-DOT_EXTERNAL_HEAP=ON"
    "-DOT_EXTERNAL_MBEDTLS=nxp-rt1170-mbedtls"
    "-DOT_STACK_ENABLE_LOG=OFF"
    "-DOT_APP_NCP=OFF"
    "-DOT_APP_RCP=OFF"
    "-DOT_RCP=OFF"
    # Default OT app cli is disabled, instead a freeRTOS version of the CLI is built
    "-DOT_APP_CLI=OFF"
    "-DOT_APP_CLI_FREERTOS=ON"
    "-DOT_APP_CLI_FREERTOS_DEBUG=ON"
    "-DOT_NXP_PLATFORM_FAMILY=imx_rt"
    "-DOT_NXP_PLATFORM=rt1170"
    "-DOT_NXP_BOARD=rt1170"
    "-DSPINEL_INTERFACE_TYPE=SPI"
    "-DOT_NXP_TRANSCEIVER=iwx12"
    "-DMULTICORE_LOGGING=OFF"
    "-DOT_COMPILE_WARNING_AS_ERROR=ON"
)

build()
{
    local builddir="${OT_CMAKE_BUILD_DIR:-build_rt1170}"
    mkdir -p "${builddir}"
    cd "${builddir}"
    mkdir -p "$1"
    cd "$1"

    # shellcheck disable=SC2068
    cmake -GNinja "${@:2}" "${OT_SRCDIR}"

    if [[ -n ${OT_CMAKE_NINJA_TARGET[*]} ]]; then
        ninja "${OT_CMAKE_NINJA_TARGET[@]}"
    else
        ninja
    fi

    cd "${OT_SRCDIR}"

    if [ $? -eq 1 ]; then
        exit 1
    fi
}

create_directory_and_build()
{
    if [ "$1" == 'all' ]; then
        build iwx12_spi "${OT_OPTIONS_TRANSCEIVER_IWX12_SPI[@]}" "-DNXP_SDK_ROOT=$NXP_RT1170_SDK_ROOT"
    elif [ "$1" == 'k32w0_uart_flow_control' ]; then
        echo "Warning: No longer maintain"
        build k32w0_uart_flow_control "${OT_OPTIONS_TRANSCEIVER_K32W0_UART_FLOW_CONTROL[@]}"
    elif [ "$1" == 'k32w0_spi' ]; then
        echo "Warning: No longer maintain"
        build k32w0_spi "${OT_OPTIONS_TRANSCEIVER_K32W0_SPI[@]}" "-DNXP_SDK_ROOT=$NXP_RT1170_SDK_ROOT"
    elif [ "$1" == 'iwx12_spi' ]; then
        build iwx12_spi "${OT_OPTIONS_TRANSCEIVER_IWX12_SPI[@]}" "-DNXP_SDK_ROOT=$NXP_RT1170_SDK_ROOT"
    else
        echo >&2 "Unsupported action: $1. Supported: all, k32w0_uart_flow_control, k32w0_spi, iwx12_spi"
        # 128 for Invalid arguments
        exit 128
    fi
}

main()
{

    # check if environmental variable NXP_RT1170_SDK_ROOT is set
    #     if not, then use "../../../" as a possible path
    if [ -z "$NXP_RT1170_SDK_ROOT" ]; then
        NXP_RT1170_SDK_ROOT="${OT_SRCDIR}/../../../"
    fi

    echo "NXP_RT1170_SDK_ROOT set to " $NXP_RT1170_SDK_ROOT

    if [ $# == 0 ]; then
        create_directory_and_build all
    else
        create_directory_and_build "$1"
    fi
}

main "$@"
